### ISSUE TITLE
push to npm

### ISSUE THREAD

**Issue by askmike** [evilive3000/poloniex-orderbook#10]
Hey! Thanks for the great library, could you possibly bump the version on NPM (to 3.1.0)?

**Comment by aeromomo** [comment]
Hey~ this is the only one that works with polo push~~~!!!!
but how do you deal with 
    this.socket.on('history', proxyMethod('history'))
?
can you make this not only for orderbook but for transations?

**Comment by evilive3000** [comment]
@aeromomo hi!
To be honest I did not understand you very well.
If you ask for API for Trade History, please look up at #11 I described the way you can log it.

It was not the main goal when I wrote it. And I think it's a bit out of the scope of `poloniex-orderbook`.

**Comment by evilive3000** [comment]
New version on NPM now.
