### ISSUE TITLE
Market Trades

### ISSUE THREAD

**Issue by LRonHubs** [evilive3000/poloniex-orderbook#11]
Is there a way to be notified when a trade happened, as well as the price and amount of the trade? ( as opposed to an arbitrary change to the bid / ask ?)

**Comment by evilive3000** [comment]
Well, I didn't implement the method for trade history on the Market.
But in a dirty way you can listen directly on the socket for event `history`.

```javascript
const PoloManager = require('poloniex-orderbook');
const poloman = new PoloManager().connect();

poloman.on('error', err => console.log(err));

poloman.socket.on('history', (channel, seq, tradeId, side, rate, amount) => {
  // ...
});

poloman.market('BTC_ETH');
```

But be aware this is a raw data. There is no checks for sequence numbers and trades order, it lays on your shoulder. You can dig a code starting from [method connect](https://github.com/evilive3000/poloniex-orderbook/blob/master/libs/manager.js#L64) in `manager.js`.

Good luck.

**Comment by evilive3000** [comment]
Just forgot to notice that if you initialize multiple markets you'll have to distinguish them by `channel` parameter in event handler.
