### ISSUE TITLE
Example from Readme is not working

### ISSUE THREAD

**Issue by Alexsey** [evilive3000/poloniex-orderbook#12]
Consider code (from Readme):
```
const PoloManager = require('poloniex-orderbook');
const poloman = new PoloManager().connect();

poloman.on('error', err => console.log(err));

poloman.on('change', info => {
  const {channel, side} = info;
  const market = poloman.market(channel);
  const top5 = market[side].slice(0, 5);

  console.log(`${side.toUpperCase()} :: ${market.seq}`);
  console.log(top5);
});

poloman.market('BTC_ETH');

// 5 seconds later
setTimeout(() => {
  poloman.disconnect();
}, 5000);
```
will output three messages. The first is extremely huge `IncomingMessage` object, the second is
```
{ Error: closed before the connection is established
    at WebSocket.close (E:\work\cybot\node_modules\poloniex-orderbook\node_modules\ws\lib\WebSocket.js:273:28)
    at WsWrapper.close (E:\work\cybot\node_modules\poloniex-orderbook\libs\ws_wrapper.js:127:13)
    at PoloManager.disconnect (E:\work\cybot\node_modules\poloniex-orderbook\libs\manager.js:89:17)
    at Timeout.setTimeout [as _onTimeout] (E:\work\cybot\src\index.js:19:11)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
  type: 'error',
  target: 
   WebSocket {
     domain: null,
     _events: 
      { open: [Object],
        message: [Object],
        error: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 0,
     bytesReceived: 0,
     extensions: {},
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _finalizeCalled: false,
     _closeMessage: null,
     _closeTimer: null,
     _closeCode: null,
     _receiver: null,
     _sender: null,
     _socket: null,
     _ultron: null,
     protocolVersion: 13,
     _isServer: false,
     url: 'wss://api2.poloniex.com',
     _req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: false,
        _last: true,
        upgrading: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET / HTTP/1.1\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: nCxNaItDt21ryuFc8t1x0A==\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\nHost: api2.poloniex.com\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/',
        _ended: false,
        res: [Object],
        aborted: 1501610731397,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] } } }
```
and the third is
```
{ msg: 'Invalid pair', channel: 'BTC_ETH' }
```

<b>BTW</b>, where did you get an wss://api2.poloniex.com endpoint?

**Comment by evilive3000** [comment]
Yeap, you're right, examples does not work now. 
I need a time to figure the reasons out.
Thank you for the note.

**Comment by evilive3000** [comment]
I figured out.
The API I used is protected with Google Recaptcha now.
So I don't see any easy way solution at the moment. Need time, sorry.

**Comment by Alexsey** [comment]
Another thing is that you are trying to reach the endpoint [wss://api2.poloniex.com](https://github.com/evilive3000/poloniex-orderbook/blob/master/libs/manager.js#L3) but in the [Poloniex docs](https://poloniex.com/support/api/) they tell to use wss://api.poloniex.com endpoint. May this be a point of concern?

**Comment by evilive3000** [comment]
No, this is not an issue, api2.poloniex.com it's an URL I took from their lib after revers engineering them. I'd say it is the feature of my lib, thanks to it I built fast and robust tool.
Read this [comment](https://github.com/evilive3000/poloniex-orderbook/issues/9#issuecomment-278300888).

**Comment by evilive3000** [comment]
All I can offer now is to send [headers](https://github.com/evilive3000/poloniex-orderbook/blob/master/examples/singlepair.js#L2) on connection to emulate browser.
Please read [here](https://github.com/evilive3000/poloniex-orderbook/blob/master/README.md), I tried to explain as detailed as it possible with my English ^_^.

**Comment by Alexsey** [comment]
Yep, I have came up with the same solution for now :( But I can't understand what do you mean under "official API". If you mean [this one](https://poloniex.com/support/api/) than it also requires to put User-Agent and Cookie header for request to path through the capcha

**Comment by evilive3000** [comment]
really? I did not know it. I don't use that API. It's sad. Hope they will change something because in current state their api useless.

**Comment by Alexsey** [comment]
Right now I'm wording with public methods and they require headers. Didn't test private yet. Support answers nothing already for a three days about how do that think this API may be used programmatically

**Comment by Alexsey** [comment]
Yup, private API also protected with captcha. Support is just ignoring tickets. It's good that you create your own implementation of Push API because sujested in official docs [autobahn](https://github.com/crossbario/autobahn-js) just has no option to pass headers in initial request
