### ISSUE TITLE
bot connection

### ISSUE THREAD

**Issue by TestniTester** [evilive3000/poloniex-orderbook#15]
hey,
is there any way to make this orderbook uses for a bot?
that 30min coockie thing is just not usable...
i want my bot to be connected 24/7
Any ideas?

**Comment by evilive3000** [comment]
Once your bot gets connected it will run until you disconnect it, you wont need reset cookies every 30 mins (it has to work in this way, but I didn't test it so long).
I don't see any way to get rid of this. Poloniex's support does not reply on requests, and as I know does not give any usable API to make authentication works in the right way. So we've got what we have.
