### ISSUE TITLE
Multiple coins do not work

### ISSUE THREAD

**Issue by Dercni** [evilive3000/poloniex-orderbook#2]
"You can create different pairs orderbooks, they will work ok simultaneously."
This does not appear to be working.

```
"use strict";

const PoloBook = require('poloniex-orderbook');

const polobook1 = (new PoloBook('btc_eth')).start();
const polobook2 = (new PoloBook('btc_etc')).start();

(function run() {
  console.log(`---===${new Date().toLocaleTimeString()}===---`);

  for(const type of ['asks', 'bids']) {
    console.log(`::::::${type}::::::`);
    for(const [rate, amount] of polobook2[type].slice(0, 5)) {
      console.log(`${rate}: ${amount}`);
    }
  }

  setTimeout(run, 1000);
})();
```

**Comment by evilive3000** [comment]
I just tried your code and everything works as expected;

``` javascript
const PoloBook = require('poloniex-orderbook');

const polobook1 = (new PoloBook('btc_eth')).start();
const polobook2 = (new PoloBook('btc_etc')).start();

(function run() {
  console.log(`---===${new Date().toLocaleTimeString()}===---`);

  for(const type of ['asks', 'bids']) {
    console.log(`::::::${type}::::::${polobook1.pair}`);
    for(const [rate, amount] of polobook1[type].slice(0, 5)) {
      console.log(`${rate}: ${amount}`);
    }

    console.log(`::::::${type}::::::${polobook2.pair}`);
    for(const [rate, amount] of polobook2[type].slice(0, 5)) {
      console.log(`${rate}: ${amount}`);
    }
  }

  setTimeout(run, 1000);
})();
```

and received next:
![output](http://imagizer.imageshack.us/a/img924/5662/jHgs56.jpg)

**Comment by evilive3000** [comment]
try to wait for few seconds, orderbook will be filled in 2-5 seconds after start.

**Comment by Dercni** [comment]
Thanks for the reply and nice code. I have been working on the orderbook for a few weeks now and being new to node.js is great to see someone else's approach.

What I am getting is the orderbook with perform the initial initialisation for both currency pairs however only the first will update using the push API.

![orderbook1](https://cloud.githubusercontent.com/assets/8362591/17827024/fadc327a-66b9-11e6-9271-a896eccca799.png)
![orderbook2](https://cloud.githubusercontent.com/assets/8362591/17827023/f8997e32-66b9-11e6-9ffb-9bd646548bf7.png)

**Comment by evilive3000** [comment]
well, I reformatted the output to make it more readable for multicoin case. And updates works fine for both coins.
![img1](http://storage8.static.itmages.com/i/16/0822/h_1471857423_9114451_1659a28f93.png)

Please do a more thorough check and let me know of your results.
Use the code below, it makes easier to read output. 

``` javascript
const polobook1 = (new PoloBook('btc_eth')).start();
const polobook2 = (new PoloBook('btc_etc')).start();

(function run() {
  console.log("");
  console.log(`---===${new Date().toLocaleTimeString()}===---`);

  for(const type of ['asks', 'bids']) {
    if (polobook1[type].length * polobook2[type].length == 0) continue;

    console.log(`::::::::::::::::::::${type}::::::::::::::::::::`);
    console.log(`\t${polobook1.pair}\t\t|\t\t${polobook2.pair}`);

    for(let i = 0; i < 5; i++) {
      const [r1, a1] = polobook1[type][i];
      const [r2, a2] = polobook2[type][i];
      console.log(`${r1}: ${a1.toFixed(4)}\t|\t${r2}: ${a2.toFixed(4)}`);
    }
  }

  setTimeout(run, 1000);
})();
```

**Comment by evilive3000** [comment]
It's look like I ran into the same problem. I need time to investigate and fix. Stay online :wink:

**Comment by evilive3000** [comment]
I think I found the weak place. It was some connection issue in the module I depend on `poloniex-unofficial`. It happened not always but time to time. And I silently suppressed it, but in the next version I will throw an error if connection is not established.

If you need quick fix before I commit new version just make a delay before calling second pair's `start`;

``` javascript
const polobook2 = new PoloBook('btc_xmr');
setTimeout(() => polobook2.start(), 3000);
```

It will reduce the probability of running into a problems, but not eliminate it ^_^

**Comment by Dercni** [comment]
Excellent, thank you. So this is an issue with poloniex-unofficial not your poloniex-orderbook.

**Comment by evilive3000** [comment]
Sorry for disappearing, but I have a good news. I bumped a new version just a few minutes ago. 
I did fix the issue. Hope you will check it and reply.

**Comment by Dercni** [comment]
Hi, thanks for the total revamp and I like the implementation of promises as opposed to callbacks. I can confirm the multicoins are working now which is great. As you are no longer using poloniex-unofficial and have written your own wrappers was the original multicoin problem resolved by the "Promise.all" line that waits for all coin pairs to be started before proceeding?

Once again thank you.
