### ISSUE TITLE
How do we know when an update happened?

### ISSUE THREAD

**Issue by joshuarossi** [evilive3000/poloniex-orderbook#5]
One of the best things about the push API is that we can respond to changes immediately, but there is no way to know when the book has changed...

**Comment by evilive3000** [comment]
Well at the moment you have not many options. One of them it's to patch the `PoloBook` instance by wrapping the handler that calls each time push event comes.

```javascript
// Create instance of PoloBook
const polobook = new PoloBook("btc_xmr");

// Remember old handler of the instace
const defHandler = polobook._onOrderTrade;

// Overwrite polobook's handler with your own.
// The method will run each time when push event comes.
// NOTE: some events may be "empty" and don't change the book state.
polobook._onOrderTrade = function myPushHandler(res, {seq}) {
  // call default handler first
  defHandler.apply(polobook, arguments);

  // do what you want
  console.log(`seq: ${seq}`);
  console.log(polobook.asks.slice(0, 1));
};

polobook
  .start()
  .catch(error => console.log(error));
```
Don't try to patch the PoloBook's class method, it wont work. So you have to overwrite each instance you've created.

I'll try to implement the feature at this weekend.
Do you want it inherits node's `EventEmitter` class or just passing some handler on creation of book?
I will look for the best options.

**Comment by joshuarossi** [comment]
hey, I forked it and did a quick prototype, not sure if it is the best way
https://github.com/joshuarossi/poloniex-orderbook

I wanted to leave as much of your code as is, because you are handling the updating of the book really well. 

Basically, all I am doing is whenever _onOrderTrade is called, I emit an "update" event and send the "res", so people can either choose to handle that event, or just be aware the book is _about_ to be updated

**Comment by joshuarossi** [comment]
Let me know if you want me to submit a PR

**Comment by evilive3000** [comment]
Yes, I'm waiting for your PR.
And thank you.

**Comment by evilive3000** [comment]
Thank you for you PR.
But I had some thoughts. Don't you think it would be more useful to get event after orderbook updates it's state? Now update triggers before.

**Comment by osnwt** [comment]
I faced the same problem: on update the book is not yet synced with the server and no way to know that the book was just reset. The user would usually consume only newTrade records, but use updated book as is. The same is for reset event.

Here is the pull request with the fix: https://github.com/evilive3000/poloniex-orderbook/pull/7

Thank you for useful module.

**Comment by evilive3000** [comment]
Starting from `v3.0` we can listen for changes `poloman.on('change', info => {})`
