### ISSUE TITLE
Loss of precision from exchange (not a poloniex-orderbook issue)

### ISSUE THREAD

**Issue by osnwt** [evilive3000/poloniex-orderbook#8]
Trying to use this orderbook, I found weird things: my orderbook was not exactly the same as shown by Poloniex via their web UI. After few experiments with an arbitrary precision math library I had a look at the data that exchange returns for returnOrderBook request. And yes, I found that for some currencies like SC there is a loss of precision just from exchange. For instance, the value 16795610.22313256 is sent in JSON as 16795610.223133. Please notice that 2 less significant digits were not sent at all. I wonder how their web UI works then, since it shows correct values with 8 digits after point.

Since you had a look at their code, could you explain that? It is not a bug of your code, but would be great to fix it if possible looking into original code. What do you think?

**Comment by evilive3000** [comment]
Good point! I will try to investigate the issue.

**Comment by osnwt** [comment]
I also found that fetching initial data returns rates as numbers with 6 digits, but push updates return strings with 8 digits. Still no answer how original web UI gets 8 digits right after boot...

**Comment by evilive3000** [comment]
Well, from v3 I left digits as they come as strings.
The only place when I treat them as Number is when I do lookups on sorted array. So there are tiny chances that we can run into a sorting problem. If there are some, let me know.

**Comment by osnwt** [comment]
For people's reference: this is due to a bug in Poloniex API v1 that returns floating point numbers to REST requests, but strings in push API. In new API v2 version there is no need for REST to get initial market state, it always sends it via web socket as strings. That's why web interface shows full precision.
